USE test1;

CREATE TABLE IF NOT EXISTS courses (
    course_code VARCHAR(20) PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    lecturer_id VARCHAR(20) NOT NULL,
    programme_name VARCHAR(100) NOT NULL,
    course_year INT NOT NULL,
    FOREIGN KEY (lecturer_id) REFERENCES lecturers(lecturer_id)
);

-- Feed 50 datasets for test
INSERT INTO courses (
    course_code,
    course_name,
    lecturer_id,
    programme_name,
    course_year
)
SELECT
    CONCAT('C', LPAD(n, 3, '0')) AS course_code,
    CONCAT('Course ', n)         AS course_name,
    CONCAT('L', LPAD((n % 10) + 1, 3, '0')) AS lecturer_id,
    CASE
        WHEN n % 3 = 0 THEN 'Degree'
        WHEN n % 3 = 1 THEN 'Diploma'
        ELSE 'Foundation'
    END AS programme_name,
    CASE
        WHEN n % 3 = 0 THEN (n % 4) + 1   -- Degree: 1-4
        WHEN n % 3 = 1 THEN (n % 3) + 1   -- Diploma: 1-3
        ELSE 1                            -- Foundation: 1 only
    END AS course_year
FROM (
    SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
    UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
    UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
    UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
    UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
    UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35
    UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
    UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45
    UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50
) t;
